build:
  version: "2.0"

accounts:
  message: "Welcome to Bank accounts related local QA APIs "
  contactDetails:
    name: "Chris Green - Developer"
    email: "chris@bank.com"
  onCallSupport:
    - 912323211123
    - 9821244425433