build:
  version: 2.0.0

cards:
  message: "Welcome to Bank loans related QA APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@bank.com"
  onCallSupport:
    - 912323232323
    - 982123425433