build:
  version: 3.0.0


cards:
  message: "Welcome to Bank loans related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@bank.com"
  onCallSupport:
    - 912323232323
    - 982123425433